version: '3.8'
services:
  main:
    build: .
    command: python3 main.py

  global:
    build: .
    volumes:
      - ./logs:/work/logs
    command: python3 global.py
    ports:
      - "11113:11113"
      - "11114:11114"

  local:
    build: .
    command: python3 local.py
    environment:
      - GLOBAL_HOSTNAME
    deploy:
      replicas: 8
